export const MEDICAL_SPECIALIZATIONS = [
  'General Medicine',
  'General Surgery',
  'Cardiology',
  'Cardiologist',
  'Dermatology',
  'Pediatrics',
  'Pediatrician',
  'Orthopedics',
  'Gynecology & Obstetrics',
  'Neurology',
  'Psychiatry',
  'Ophthalmology',
  'ENT',
  'Oncology',
  'Radiology',
  'Anesthesiology',
  'Emergency Medicine',
  'Gastroenterology',
  'Nephrology',
  'Pulmonology',
  'Urology',
  'Endocrinology',
  'Dentistry',
  'Physiotherapy',
] as const;
